name = input("enter your name:")
age = int(input("enter your age:"))
marks = float(input("enter your marks:"))
print("Welcome:", name)
print(type(name))
print("Age", age)
print(type(age))
print("Your Marks is:", marks)
print(type(marks))